import { CALL_INTENT_SIGNAL_TYPE, TIME_OF_DAY_PREFERENCE_SIGNAL_TYPE, WALK_PATTERN_SIGNAL_TYPE, WORK_HOURS_SIGNAL_TYPE, type SignalType } from "../types.js";

export const onePerUserSignals = [
    WALK_PATTERN_SIGNAL_TYPE,
    WORK_HOURS_SIGNAL_TYPE,
    CALL_INTENT_SIGNAL_TYPE,
    TIME_OF_DAY_PREFERENCE_SIGNAL_TYPE,
];
